= Summit 2023: ROSA Booth Demo

[WARNING]
====
The steps on this page should only be run ONCE at the very beginning.  Do not run these again.  This is only for a fresh environment.
====

== Connect to your bastion VM

In the terminal window to the right, connect to the bastion VM (you can click the command below to have it copied and executed automatically):

[source,sh,role=execute]
----
ssh %rosa_bastion_user_name%@bastion.%rosa_subdomain_base%
----

The password for the user %rosa_bastion_user_name% is `%rosa_user_password%`

== Ensure ELB service role exists

Run the following to check for the role and create it if it is missing.

[source,sh,role=execute]
----
aws iam get-role --role-name "AWSServiceRoleForElasticLoadBalancing" || aws iam create-service-linked-role --aws-service-name "elasticloadbalancing.amazonaws.com"
----

== Install a ROSA w/HCP cluster

=== VPC

. Create the VPC.
+
[source,sh]
----
curl -s https://raw.githubusercontent.com/openshift-cs/rosaworkshop/master/rosa-workshop/rosa/resources/setup-vpc.sh | bash
----

. There are two commands that are output from the script. Set those as environment variables to make running the create cluster command easier. Copy them from the output and run them.
+
[source,sh]
----
export PUBLIC_SUBNET_ID=<public subnet id here>
export PRIVATE_SUBNET_ID=<private subnet id here>
----

. Confirm that the environment variables are, in fact, set.
+
[source,sh,role=execute]
----
echo "Public Subnet: $PUBLIC_SUBNET_ID"; echo "Private Subnet: $PRIVATE_SUBNET_ID"
----
+
.Sample Output
[source,text]
----
Public Subnet: subnet-0faeeeb0000000000
Private Subnet: subnet-011fe340000000000
----
+
[WARNING]
====
If one or both are blank, do not proceed and ask for assistance.
====

=== OIDC Configuration

[source,sh]
----
export OIDC_ID=$(rosa create oidc-config --mode auto --managed --yes -o json | jq -r '.id'); echo $OIDC_ID;
----

.Sample Output
[source,text]
----
23o3doeo86adgqhci4jl000000000000
----

=== Create the cluster

. Run the following command to create the account-wide roles:
+
[source,sh]
----
rosa create account-roles --mode auto --yes
----

. Run the following command to create the cluster:
+
[source,sh]
----
rosa create cluster --cluster-name rosa-${GUID} \
    --subnet-ids ${PUBLIC_SUBNET_ID},${PRIVATE_SUBNET_ID} \
    --hosted-cp \
    --oidc-config-id $OIDC_ID \
    --sts --mode auto --yes
----
+
In about 10 minutes the control plane and API will be up, and about 5-10 minutes after, the worker nodes will be up and the cluster will be completely usable.  This cluster will have a control plane across three AWS availability zones in your selected region, in a Red Hat AWS account and will also create 2 worker nodes in your AWS account.

=== Check installation status
. You can run the following command to check the detailed status of the cluster:
+
[source,sh,role=execute]
----
rosa describe cluster --cluster rosa-${GUID}
----
+
or, you can also watch the logs as it progresses:
+
[source,sh,role=execute]
----
rosa logs install --cluster rosa-${GUID} --watch
----

. Once the state changes to “ready” your cluster is now installed. It may take a few more minutes for the worker nodes to come online. In total this should take about 15 minutes.

=== Create the admin user in the ROSA Cluster

. Run this command to create the admin user. The output is saved locally in case you get logged out.
+
[source,sh,role=execute]
----
rosa create admin --cluster rosa-${GUID} | tee ${HOME}/login-command.cmd
----

. Wait about 2 minutes for it to set up. Copy the command and paste it in and run it to log in.

== Configure Cloudwatch

. Run the following to configure the cluster to forward logs to cloudwatch.
+
[source,sh]
----
curl -s https://raw.githubusercontent.com/openshift-cs/rosaworkshop/master/rosa-workshop/ostoy/resources/configure-cloudwatch.sh | bash
----

. After a few minutes, you should begin to see log groups inside of AWS CloudWatch. Repeat this command until you do or continue if you don't want to wait.
+
[source,sh,role=execute]
----
aws logs describe-log-groups --log-group-name-prefix rosa-${GUID}
----
+
.Sample Output
[source,json,options=nowrap]
----
{
    "logGroups": [
        {
            "logGroupName": "rosa-fxxj9.audit",
            "creationTime": 1682098364311,
            "metricFilterCount": 0,
            "arn": "arn:aws:logs:us-east-2:511846242393:log-group:rosa-fxxj9.audit:*",
            "storedBytes": 0
        },
        {
            "logGroupName": "rosa-fxxj9.infrastructure",
            "creationTime": 1682098364399,
            "metricFilterCount": 0,
            "arn": "arn:aws:logs:us-east-2:511846242393:log-group:rosa-fxxj9.infrastructure:*",
            "storedBytes": 0
        }
    ]
}
----

== Log into OpenShift Web Console

. Get the OpenShift Web console url
+
[source,sh,role=execute]
----
oc whoami --show-console
----

. Click on `htpasswd`
. User: `cluster-admin`
. PW: from admin user command above

== Install the ACK Operator

. Login to your OpenShift cluster's web console (if you aren't already).
. On the left menu, click on "Operators > OperatorHub".
. In the filter box enter "S3" and select the "AWS Controller for Kubernetes - Amazon S3"
. If you get a pop-up saying that it is a community operator, just click "Continue".
. Click "Install" in the top left.
. Ensure that "All namespaces on the cluster" is selected for "Installation mode".
. Ensure that "ack-system" is selected for "Installed Namespace".
. Under "Update approval" ensure that "Manual" is selected.
+
[WARNING]
====
Make sure to select "Manual Mode" so that changes to the Service Account do not get overwritten by an automatic operator update.
====

. Click "Install" on the bottom.

. Approve the operator installation. Click the *Approve* button.

. You will see that installation is taking place. The installation won't complete until the next step is finished.
So please proceed.

. Run this script to finish setup.
+
[source,sh]
----
curl -s https://raw.githubusercontent.com/openshift-cs/rosaworkshop/master/rosa-workshop/ostoy/resources/setup-s3-ack-controller.sh | bash
----

. Confirm that the environment variables are set. Run:
+
[source,sh,role=execute]
----
oc describe pod ack-s3-controller -n ack-system | grep "^\s*AWS_"
----
+
.Sample Output
[source,text,options=nowrap]
----
AWS_ROLE_ARN:                 arn:aws:iam::948540395585:role/ack-s3-controller
AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
----

== Run these to setup the demo.

. Run the following to set up this demo.
+
[source,sh]
----
wget -q https://raw.githubusercontent.com/0kashi/bookbag-rosa-summit2023-booth/main/workshop/content/setup-rosa-demo.sh
chmod +x setup-rosa-demo.sh
./setup-rosa-demo.sh
----
